### PR TITLE
Bug Fixes

### LINKED ISSUE #1232: Edit Contract doesn't retain keywords
When using the edit contract feature, the existing keywords are eliminated.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11715933-edit-contract-doesn-t-retain-keywords?utm_campaign=plugin&utm_content=tracker%2F1516753&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1516753&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1269: Not able to edit a contract
I'm getting the following error when trying to save a change to an existing contract:
```
Error: $scope.contract.productKeywords.split is not a function
$scope.ProductModalInstance/$scope.saveContract@http://127.0.0.1:50521/html/controllers/contracts.js:239:76
gb.prototype.functionCall/<@http://127.0.0.1:50521/html/vendors/angular.min.js:178:66
jc[c]</<.compile/</</f@http://127.0.0.1:50521/html/vendors/angular.min.js:195:177
Yd/this.$get</h.prototype.$eval@http://127.0.0.1:50521/html/vendors/angular.min.js:113:28
Yd/this.$get</h.prototype.$apply@http://127.0.0.1:50521/html/vendors/angular.min.js:113:305
jc[c]</<.compile/</<@http://127.0.0.1:50521/html/vendors/angular.min.js:195:227
ne/c/<@http://127.0.0.1:50521/html/vendors/angular.min.js:31:223
r@http://127.0.0.1:50521/html/vendors/angular.min.js:7:288
ne/c@http://127.0.0.1:50521/html/vendors/angular.min.js:31:207
```
Mac OS 10.9.5, Firefox 37.0.2

### LINKED ISSUE #1289: Cannot update a contract that has keywords
I can't update a contract when it has keywords.

Version: 0.4.0
Steps to repeat:

1. Create a new contract (mine had description and images) and give it keywords.
2. Edit the description of the contract and try pressing save, it shouldn't do anything and the console will log the error below.
3. Remove the keywords from the contract, hit save, it will save.
4. Edit the contract again, add the tags back, hit save, it will save.

```
  TypeError: $scope.contract.productKeywords.split is not a function
      at h.$scope.saveContract (contracts.js:240)
      at angular.min.js:16090
      at f (angular.min.js:20011)
      at h.$eval (angular.min.js:12870)
      at h.$apply (angular.min.js:13017)
      at HTMLButtonElement.<anonymous> (angular.min.js:20014)
      at angular.min.js:3048
      at r (angular.min.js:323)
      at HTMLButtonElement.c (angular.min.js:2797)(anonymous function) @   angular.min.js:10766(anonymous function) @ angular.min.js:7337h.$apply @   angular.min.js:13018(anonymous function) @ angular.min.js:20014(anonymous function) @   angular.min.js:3048r @ angular.min.js:323c @ angular.min.js:2797
```

### PR DESCRIPTION
**Pull request by hoffmabc**
Fixes:
* Fixes #1289 
* Fixes #1232 
* Fixes #1269 
* @drwasho bug where BTC->USD/EUR pricing not showing

### CODE REVIEW

File: html/controllers/contracts.js [hunk 1]
```diff
@@ -237,8 +238,16 @@ angular.module('app')
                             }
                         };
 
-                        var keywords = ($scope.contract.productKeywords[0]) ? $scope.contract.productKeywords.split(',') : [];
-                        $.each(keywords, function(i, el) {
+                        if(typeof($scope.contract.productKeywords) === 'string' && $scope.contract.productKeywords !== "") {
```
Comment (gubatron) [inline html/controllers/contracts.js]: is there some sort of javascript utils file?

it'd be nice to have a:
```
StringUtils.isNonEmptyString($scope.contract.productKeywords)
```
and start abstracting away all the Javascript good practices.
